# Intraclass Correlation Coefficient a.k.a. repeatability {-}

## Explanation
### The basics
Repeatability, as measured by the intraclass correlation coefficient (ICC), is a unitless way to see if measurements are consistent. If you measure the same thing more than once, are you going to get a similar answer?

This is usually calculated by comparing (in some way, methods vary) how much variation there is within a given object/individual measured versus the variation over all measurements of all individuals.

Here's an example using SAS sample data [@PROCNESTEDVariability].

```{r ICC_concept_graph}

   # title 'Calcium Concentration in Turnip Leaves'
   #       '--Nested Random Model';
   # title2 'Snedecor and Cochran, ''Statistical Methods'''
   #        ', 1976, p. 286';
   # data Turnip;
   #    do Plant=1 to 4;
   #       do Leaf=1 to 3;
   #          do Sample=1 to 2;
   #             input Calcium @@;
   #             output;
   #          end;
   #       end;
   #    end;
   #    datalines;
   # 3.28 3.09 3.52 3.48 2.88 2.80 2.46 2.44
   # 1.87 1.92 2.19 2.19 2.77 2.66 3.74 3.44
   # 2.55 2.55 3.78 3.87 4.07 4.12 3.31 3.31
   # ;
   # 
   # proc nested data=Turnip;
   #    classes plant leaf;
   #    var calcium;
   # run;

Plant <- 1:4
Leaf <- 1:3
Sample = 1:2

turnip <- expand.grid(Sample=Sample, Leaf=Leaf, Plant=Plant)

turnip$calcium <- c(3.28, 3.09, 3.52, 3.48, 2.88, 2.80, 2.46, 2.44, 1.87, 1.92, 2.19, 2.19, 2.77, 2.66, 3.74, 3.44, 2.55, 2.55, 3.78, 3.87, 4.07, 4.12, 3.31, 3.31)


library(ggplot2)

ggplot(data = turnip,
       mapping = aes(x = Plant,
                     y = calcium,
                     color = as.factor(Leaf),
                     shape = as.factor(Sample))) +
  geom_point()


```


### More technical

#### Questions and data types
Example problem structures and types of data you need.

#### Key assumptions and limitations

##### Assumptions
This is how to know if you can use the method.

- Most assume Gaussian/normal data, but Nakagaw and Schielzeth [-@nakagawaRepeatabilityGaussianNonGaussian2010a] extend to non-normal data.

##### Limitations
It's important to pick the right ICC calculation for your study design, though at least one paper says you can do all three [@liljequistIntraclassCorrelationDiscussion2019] and compare.

Bailey and Byrnes [-@baileyNewOldMethod1990] suggest how to calculate a suitable sample size for studies based on the measurement error found.

Two thresholds are listed on the wikipedia page [@IntraclassCorrelation2024], but neither paper provides justifications for their thresholds.  (One study [@kooGuidelineSelectingReporting2016] has an erratum due to a key equation being incorrect in the feature comparison table [@ErratumGuidelineSelecting2017].)  

More realistically, you need to know what it actually means for your data and concepts being test [@wilsonHowShouldWe2018].  There's nothing magic about any particular threshold.

#### Key distinctions among related methods
"Generalizability theory" ("G-Theory") is related to "classic test theory" which appears to contain repeatability and ICCs [@vispoelApplicationsGeneralizabilityTheory2018].This seems to provide a broader range of indices of how reliable measurements are, but may not be necessary for simple applications.

#### Implementation and controversies
[@liljequistIntraclassCorrelationDiscussion2019] claim it doesn't matter which ICC method you use, and that if you use all three main methods you can use any differences to suggest what type of bias you may have in measurements.

[@curryRepeatabilityIntraclassCorrelation2016] describe how to implement in R and SAS.


### Most technical
The key citations.

## Examples "in the wild"
Citations and what is useful in the paper.
    
The most updated guideline is [@tenhoveUpdatedGuidelinesSelecting2024]
